# Generated by Django 5.0.6 on 2024-07-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=255),
        ),
    ]
